services:
  - type: web
    name: vite-react-app
    env: node
    buildCommand: npm run build
    startCommand: npm start
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
envVars:
  - key: NODE_ENV
    value: production
