services:
  - type: web
    name: vite-react-app
    env: node
    buildCommand: npm run build
    startCommand: npm start
    build:
      env:
        - NODE_ENV=production
    plan: free
    routes:
      - type: rewrite
        source: /*  # This wildcard pattern matches all paths
        destination: /index.html
